site_name: CIEE

theme:
  name: material
  language: pt
  logo: img/logowhite.png
  favicon: img/logo.png
  palette:
    scheme: slate

nav:
  - Inicio: index.md
  - Planejamento:
    - Escolha do site: planejamento/escolha_site.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise_requisitos/perfil_usuario.md
    - Personas: analise_requisitos/personas.md
    - Análise de Tarefas: analise_requisitos/analise_tarefas.md
  - Apresentações: apresentacoes.md
