site_name: CIEE

nav:
  - Inicio: index.md
  - Planejamento:
    - Equipe: planejamento/equipe.md
    - Escolha do site: planejamento/escolha_site.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo.md
